# Generated by Django 3.2.6 on 2021-10-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_desc', models.TextField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.team')),
            ],
        ),
    ]
