# Generated by Django 3.2.6 on 2021-10-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_task_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
