# Generated by Django 3.2.6 on 2021-10-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_team_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='img_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
