# Generated by Django 3.2.6 on 2021-10-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyTeam', models.TextField()),
                ('prevExp', models.TextField()),
                ('preference', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
                ('expect', models.TextField(null=True)),
                ('team', models.ManyToManyField(related_name='appliedTo', to='users.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
