# Generated by Django 3.2.6 on 2021-10-28 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20211026_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='preference',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
